apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xlabeller-pvc
  namespace: katech-xlabeller
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
