apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: katech-xlabeller-pvc
  namespace: katech-xlabeller
spec:
  storageClassName: katech-dataset
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
