apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "mariadb.name"}}-pvc"
  namespace: katech-marketplace
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
